export const OTHER_BANK_VALUE = 'other';

// Top banks in Colombia for faster selection in payment flows.
export const TOP_COLOMBIA_BANKS: string[] = [
  'Bancolombia',
  'Banco de Bogota',
  'Davivienda',
  'BBVA Colombia',
  'Banco de Occidente',
  'Scotiabank Colpatria',
  'Banco Popular',
  'Banco AV Villas',
];

// Extended catalog for Colombia transfers.
// Includes commercial banks and frequently used supervised entities.
// Keep this list reviewed periodically.
export const COLOMBIA_BANKS: string[] = [
  'Ban100',
  'Bancamia',
  'Bancolombia',
  'Banco Agrario de Colombia',
  'Banco AV Villas',
  'Banco de Bogota',
  'Banco de Occidente',
  'Banco Falabella',
  'Banco Finandina',
  'Banco GNB Sudameris',
  'Banco Itaú Colombia',
  'Banco Pichincha',
  'Banco Popular',
  'Banco Santander Colombia',
  'Banco Serfinanza',
  'Banco Unión Colombia',
  'Banco W',
  'Banco Caja Social',
  'BBVA Colombia',
  'BTG Pactual Colombia',
  'Citibank Colombia',
  'Coofinep',
  'Confiar',
  'Cooperativa Financiera de Antioquia',
  'Davivienda',
  'Fincomercio',
  'Giros y Finanzas',
  'Iris CF',
  'JPMorgan Colombia',
  'Lulo Bank',
  'Mibanco',
  'Moviired',
  'Nequi',
  'Nu Colombia',
  'RappiPay',
  'Scotiabank Colpatria',
  'Uala',
  'Banco Cooperativo Coopcentral',
  'Bancoomeva',
  'Coltefinanciera',
  'Comultrasan',
  'Credifinanciera',
  'Crezcamos',
  'JFK Cooperativa Financiera',
  'Mundo Mujer',
  'Tuya',
  'Vusion',
  'Finandina',
  'PSE',
  'Transfiya',
  'Daviplata',
  'Movii',
  'Tpaga',
  'Ding',
].filter((value, index, self) => self.indexOf(value) === index);
